### ISSUE TITLE
unable to send to s3

### ISSUE THREAD

**Issue by Frederic-de-Lavenne** [leonstafford/wp2static-addon-s3#50]
Hello,
I'm unable to send the static content to s3.
When i clic on generate static i have the following error:

` PHP Fatal error:  Uncaught Aws\\Exception\\InvalidRegionException: Region must be a valid RFC host label. in /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/ClientResolver.php:543\nStack trace:\n#0 /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/ClientResolver.php(323): Aws\\ClientResolver::_apply_endpoint_provider(Object(Aws\\Endpoint\\Partition), Array, Object(Aws\\HandlerList))\n#1 /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/AwsClient.php(199): Aws\\ClientResolver->resolve(Array, Object(Aws\\HandlerList))\n#2 /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/AwsClient.php(447): Aws\\AwsClient->__construct(Array)\n#3 /var/www/html/wp-content/plugins/wp2static-addon-s3/src/Deployer.php(255): Aws\\AwsClient::factory(Array)\n#4 /var/www/html/wp-content/plugins/wp2static-addon-s3/src/Deployer.php(286): WP2StaticS3\\Deployer::cloudfrontClient()\n#5 /var/www/html/wp-content/plugins/wp2static-addon-s3/src/Deployer.php(309): W in /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/ClientResolver.php on line 543`

Version 1.0.1-dev
i have completed the setting with region eu-west-1

Any idea ?

**Comment by john-shaffer** [comment]
Can you double check and make sure that there are no extra spaces or anything?  E.g., you may have `"eu-west-1 "` instead of `"eu-west-1"`.
